### ISSUE TITLE
openwisp_users.models.User doesn't declare an explicit app_label

### ISSUE THREAD

**Issue by DavidMeu** [openwisp/openwisp-ipam#122]
Recieving the following error for `manage.py makemigrations` after extending both `openwisp_ipam ` and  `opwnwisp_users `apps.
```
    from openwisp_ipam.base.models import AbstractIpAddress, AbstractSubnet
  File "C:\Users\DavidMeushar(CPIL)\OneDrive - Cyberproof\Desktop\ipam-service\venv\lib\site-packages\openwisp_ipam\base\models
.py", line 10, in <module>
    from openwisp_users.models import Organization
  File "C:\Users\DavidMeushar(CPIL)\OneDrive - Cyberproof\Desktop\ipam-service\venv\lib\site-packages\openwisp_users\models.py"
, line 18, in <module>
    class User(AbstractUser):
  File "C:\Users\DavidMeushar(CPIL)\OneDrive - Cyberproof\Desktop\ipam-service\venv\lib\site-packages\django\db\models\base.py"
, line 113, in __new__
    raise RuntimeError(
RuntimeError: Model class openwisp_users.models.User doesn't declare an explicit app_label and isn't in an application in INSTA
LLED_APPS.
```

**Comment by pandafy** [comment]
Hi @DavidMeu! 
This issue seems to be fixed in the latest master. Check https://github.com/openwisp/openwisp-ipam/pull/58.
I suggest you to use the master branch of openwisp-ipam. 
Please use one of the support channels described here if have any doubts: https://openwisp.org/support.html

**Comment by DavidMeu** [comment]
Thank you!

**Comment by DavidMeu** [comment]
@pandafy 
Saw you recently pushed to req.
Please see:
https://github.com/openwisp/openwisp-ipam/issues/125

**Comment by DavidMeu** [comment]
@pandafy 
Shouldn't that be on a stable version of `openwisp-ipam`?

> I suggest you to use the master branch
Don't think this is a best practice.

**Comment by pandafy** [comment]
> Don't think this is a best practice.

We are in works for publishing a new release of OpenWISP. But until then, the only way to use fixes is to use the master branch. You can pin to a specific commit if you want to.
