### ISSUE TITLE
Best DB to Interact with IPAM

### ISSUE THREAD

**Issue by DavidMeu** [openwisp/openwisp-ipam#124]
Not sure this is the correct place to put this issue.

I've deployed ipam app but I'm not sure which DB I should use (mongo, postgres etc..).
I tried using mongodb (with [djongo ](https://github.com/nesdis/djongo) module) but got allot of errors.

[sql decode errors](https://stackoverflow.com/questions/69871853/recieving-sqldecodeerror-for-djongo-migration)

Anyone tried migrating with mongodb?

Any insight will be appreciated,
Thank you.

**Comment by nemesisdesign** [comment]
Regarding which DB you should use, that's not a question I can reply to because it depends on your requirements. Use any DB which has a database backend widely supported by django: https://docs.djangoproject.com/en/3.2/ref/databases/.

**Comment by DavidMeu** [comment]
@nemesisdesign 
Thank you for the response.
Basically I wanted to see if there any one that applied a migration with mongodb.

**Comment by nemesisdesign** [comment]
> @nemesisdesign Thank you for the response.

You're welcome!

> Basically I wanted to see if there any one that applied a migration with mongodb.

In the django world we tend to keep our life easy and stick with an SQL DB which is very well supported, the migration framework nowadays works really well and changes of schemas are really not that problematic.

In OpenWISP we use also non relational DBs like InfluxDB and elasticsearch for timeseries data, I personally think non-relational DB are great for specific use cases, but for what we do here, classic SQL databases work best.

Best luck!
