### ISSUE TITLE
[deps] Update dependencies

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-ipam#21]
Add support for django 3.0 and update dependencies.

Drop support for python 3.5, add 3.6 and 3.7 to the travis build.

**Comment by varadhbhatnagar** [comment]
Working on this.

**Comment by IAmAMissingColon** [comment]
@varadhbhatnagar Are you still working on this ! otherwise I'll take it :smile:

**Comment by varadhbhatnagar** [comment]
> @varadhbhatnagar Are you still working on this ! otherwise I'll take it

Please go ahead and take it up. I have been a little caught up in work lately.

**Comment by nepython** [comment]
@IAmAMissingColon , shall I **please** take this issue? :smiley:

**Comment by IAmAMissingColon** [comment]
Um! Okay :smile:
