### ISSUE TITLE
Organization field on ip address is redundant

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-ipam#28]
The organization field on the ip address model is redundant because it's already defined in Subnet hence It can be removed.

In openwisp-firmware-upgrader the organization is stored in the Category model, and the organization is inferred by the category: https://github.com/openwisp/openwisp-firmware-upgrader/blob/master/openwisp_firmware_upgrader/base/admin.py#L43 

We can do something similar in this module.

**Comment by lehone-hp** [comment]
Working on this.

**Comment by nemesisdesign** [comment]
@lehone-hp sup?

**Comment by lehone-hp** [comment]
> @lehone-hp sup?

I have been working on my project proposal and demo before deadline approaches so I kept this task on a pause. Will resume after I submit them
