### ISSUE TITLE
[api] Add ScopedThrottling

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-ipam#34]
Add ScopedThrottling as we do in [openwisp-firmware-upgrader](https://github.com/openwisp/openwisp-firmware-upgrader).

**Comment by ManishShah120** [comment]
I would like to work on this issue. @nemesisdesign

**Comment by nemesisdesign** [comment]
Go for it, @ManishShah120, take a look at https://github.com/openwisp/openwisp-firmware-upgrader/pull/75/files
