### ISSUE TITLE
[IPAM/change] Add default permissions to default groups

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-ipam#55]
Create a data migration to create the default permissions for the default group: Administrator and Operator.

Administrator should be granted all permissions on `Subnet` and `IpAddress`.
Operator should have only view permission on `Subnet` while it should be granted all permissions on `IpAddress`.

For reference, see how it's done in other modules (so a certain degree of consistency can also be maintained):

- [openwisp-controller](https://github.com/openwisp/openwisp-controller/blob/master/openwisp_controller/config/migrations/0015_default_groups_permissions.py)
- [openwisp-radius](https://github.com/openwisp/openwisp-radius/blob/master/openwisp_radius/migrations/0004_default_permissions.py)
-  [openwisp-network-topology](https://github.com/openwisp/openwisp-network-topology/blob/master/openwisp_network_topology/migrations/0005_default_operator_permission.py)

**Comment by ManishShah120** [comment]
@nemesisdesign, I am interested in working on this issue.

**Comment by nemesisdesign** [comment]
@ManishShah120 go for it!

**Comment by codesankalp** [comment]
@ManishShah120 Are you still working on this issue?

**Comment by ManishShah120** [comment]
Yeah @codesankalp
