### ISSUE TITLE
[feature] Add django-reversion as in other openwisp modules

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-ipam#57]
In this module django-reversion would be useful, like as we have in openwisp-controller.

**Comment by ManishShah120** [comment]
Hey @nemesisdesign, I am interested in working on this issue. As I will be contributing to this project for the first time, I am unable to figure out the level of this issue, like is this issue suitable for any `first-time` contributor. Also, it will be of great help if you can reference or provide me with some resources which I can follow to solve this issue.
--Thank You

**Comment by nemesisdesign** [comment]
@ManishShah120 welcome! Look for "reversion" in the code of openwisp-controller, also look django-reversion on google to understand what is all about.
