### ISSUE TITLE
[api] Add DjangoModelPermissions 

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-ipam#59]
Add [DjangoModelPermissions](https://www.django-rest-framework.org/api-guide/permissions/#djangomodelpermissions) to the API views, update tests if needed.

**Comment by winter-code** [comment]
@nemesisdesign Is there a doc that specifies which views can have what permissions?

**Comment by nemesisdesign** [comment]
@winter-code it's defined here: https://github.com/openwisp/openwisp-ipam/issues/55
But it's not necessary to specify the permissions in the code. It's handled automatically by the permission class of DRF.

**Comment by hasanmdarif** [comment]
hey @nemesisdesign i want to contribute. Can you please elaborate more?

**Comment by ManishShah120** [comment]
@nemesisdesign , I would like to take upon this issue. If it's not resolved yet.

**Comment by nemesisdesign** [comment]
This was implemented a while ago and we forgot to mention it and close it.
