### ISSUE TITLE
[api] Refactor URLs to use path()

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-ipam#60]
Refactor URLs to use [django.urls.path](https://docs.djangoproject.com/en/3.1/ref/urls/#path).

**Comment by parnus01** [comment]
May i do this PR ?

**Comment by nemesisdesign** [comment]
@parnus01 sure go ahead!

**Comment by parnus01** [comment]
@nemesisdesign  which related file for this issue ?

**Comment by parnus01** [comment]
Thank you ! will create PR after 1 Oct.
