### ISSUE TITLE
[api] Implement multitenancy in API

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-ipam#61]
The API of this module currently does not respect multi-tenancy, we should implement it using the [Django REST Framework permission classes of openwisp-users](https://github.com/openwisp/openwisp-users/#django-rest-framework-permission-classes).

**Comment by DaffyTheDuck** [comment]
Hi! can I have some more information like docs to read or something like that ?

**Comment by nemesisdesign** [comment]
@DaffyTheDuck users should only be able to see objects of the organizations they belong from the API.
See how it's implemented in openwisp-radius:

- https://github.com/openwisp/openwisp-radius/blob/master/openwisp_radius/api/views.py#L56

My suggestion is to implement a few tests that create 2 organizations (orgA and orgB) and 1 user for each organization, then create one object (eg: 1 ip address) for orgA and another object for orgB, ensure if user of orgA fetches the list view it sees only objects of of orgA, same for user of orgB, could be 1 test for subnet and 1 for ip.
The test should fail, then when adding the permission class from openwisp-users should pass.

Then repeat for the detail API view, the outcome there may be different from the list though (maybe the object is not found at all), but try and let me know what you find.

@atb00ker should also be able to guide you with this, so with the guidance of both you should be able to do it! :+1:

**Comment by DaffyTheDuck** [comment]
I'll try to work on it :smiley:

**Comment by DaffyTheDuck** [comment]
Anyone can work on this issue if they want, i'm quite busy in my college works :sweat_smile: , if no one picks it,  i'll :smile:

**Comment by Purhan** [comment]
WIP for this, I will push the code after some time :smile:
