### ISSUE TITLE
No module named 'openwisp_users.api.mixins'

### ISSUE THREAD

**Issue by zhangjianpinghik** [openwisp/openwisp-ipam#94]
when i install ipam  for development:
cd openwisp-ipam
pip install -e .
pip install -r requirements-test.txt
pip install openwisp-users
pip install openwisp-utils
cd tests/
./manage.py migrate
but the error occured：
File "/root/openwisp-ipam-master/openwisp-ipam-master/openwisp_ipam/api/views.py", line 9, in <module>
    from openwisp_users.api.mixins import FilterByOrganizationManaged, FilterByParentManaged
ModuleNotFoundError: No module named 'openwisp_users.api.mixins'
i locate the openwisp_users , mixins.py is not in api folder,but in the parent folder，i change the ipam code 
 from openwisp_users.api.mixins import FilterByOrganizationManaged, FilterByParentManaged to from openwisp_users.mixins import FilterByOrganizationManaged, FilterByParentManaged
but it not works.  who can help me ? thks.

**Comment by ManishShah120** [comment]
The new changes are not released yet, you can get it with this:-
`pip install -U https://github.com/openwisp/openwisp-users/archive/master.zip`

**Comment by nemesisdesign** [comment]
you should not do:

```
pip install openwisp-users
pip install openwisp-utils
```

Why are you doing that?

The current openwisp-users master will be pulled in when doing `pip install -e .`, see https://github.com/openwisp/openwisp-ipam/blob/master/requirements.txt.

When you install openwisp-users again you overwrite it.
