### ISSUE TITLE
can not Install  for development

### ISSUE THREAD

**Issue by zhangjianpinghik** [openwisp/openwisp-ipam#95]
Installation for development
Install openwisp-ipam for development using following commands:

git clone https://github.com/openwisp/openwisp-ipam.git
cd openwisp-ipam
pip install -e .
pip install -r requirements-test.txt
Launch the development sever:

cd tests/
./manage.py migrate
./manage.py createsuperuser
./manage.py runserver

the error is :
  File "/root/openwisp-ipam-master/openwisp-ipam-master/openwisp_ipam/admin.py", line 18, in <module>
    from .api.views import HostsSet
  File "/root/openwisp-ipam-master/openwisp-ipam-master/openwisp_ipam/api/views.py", line 9, in <module>
    from openwisp_users.mixins import FilterByOrganizationManaged, FilterByParentManaged
ImportError: cannot import name 'FilterByOrganizationManaged'

**Comment by Purhan** [comment]
@zhangjianpinghik This is probably because of the same reason as explained here: https://github.com/openwisp/openwisp-ipam/issues/94

Please do not create these issues here. Ask these questions in the [Gitter chat](https://gitter.im/openwisp/general)

**Comment by zhangjianpinghik** [comment]
@Purhan  it still not works.

**Comment by Purhan** [comment]
@zhangjianpinghik Did you run this command?
```
pip install https://github.com/openwisp/openwisp-users/tarball/master
```

After that, did you check its version? What do you get when you type this:
```
pip show openwisp-users
```

**Comment by zhangjianpinghik** [comment]
0.6.0a0

**Comment by zhangjianpinghik** [comment]
@Purhan 0.6.0a0

**Comment by zhangjianpinghik** [comment]
@Purhan 
pip install -U https://github.com/openwisp/openwisp-users/archive/master.zip
the version is:0.6.0a0

**Comment by Purhan** [comment]
@zhangjianpinghik Are you using a virtual environment? If not, please create a virtual environment and repeat the setup inside it.
Instructions for creating a virtual environment: https://docs.python.org/3/library/venv.html
Make sure you activate it as well:
```bash
python3 -m venv venv

source venv/bin/activate
```

**Comment by zhangjianpinghik** [comment]
@Purhan  not  virtual environment

**Comment by zhangjianpinghik** [comment]
@Purhan  i change another server install it step by step following Setup (integrate in an existing Django project)

it still not works. the error is:
RuntimeError: Model class allauth.account.models.EmailAddress doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

**Comment by devkapilbansal** [comment]
@zhangjianpinghik please make sure `allauth` is present in INSTALLED_APPS in settings.py file

**Comment by pandafy** [comment]
@zhangjianpinghik please use any one of [OpenWISP's support channels](https://openwisp.org/support.html) to ask for help, since this is our bug tracker. I suggest adding link to this issue to provide context for future queries. We will try to help you. 

Thank you very much for showing interest in OpenWISP.
