### ISSUE TITLE
[bug] Queries using organization name

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-ipam#99]
The code has some instances where subnets are created or retrieved from the database using organization name. Since organization name is not unique, we should use another unique parameter like `slug`

**Comment by nemesisdesign** [comment]
Found a similar but different issue: #101.

**Comment by pandafy** [comment]
I searched the codebase for "name" keyword and I didn't find any instance of Organization object being queried with `name` field. It might be possible that such instances were fixed in https://github.com/openwisp/openwisp-ipam/pull/97. 

In my findings, this issue can be closed.
